# Generated by Django 6.0.4 on 2026-06-05 00:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Stylist',
                'verbose_name_plural': 'Stylists',
                'db_table': 'stylists',
            },
        ),
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hair salon',
                'verbose_name_plural': 'Hair salons',
                'db_table': 'hair_salons',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(help_text='Almacena la contraseña encriptada. Usa django.contrib.auth.hashers.make_password()', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='HorarioEstilista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('stylist', models.ForeignKey(db_column='stylist_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sac.estilista')),
            ],
            options={
                'verbose_name': 'Stylist schedule',
                'verbose_name_plural': 'Stylist schedules',
                'db_table': 'stylist_schedules',
            },
        ),
        migrations.AddField(
            model_name='estilista',
            name='hair_salon',
            field=models.ForeignKey(db_column='hair_salon_id', on_delete=django.db.models.deletion.CASCADE, related_name='estilistas', to='sac.peluqueria'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('hair_salon', models.ForeignKey(db_column='hair_salon_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='sac.peluqueria')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('stylist', models.ForeignKey(db_column='stylist_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_asignadas', to='sac.estilista')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_servicio', to='sac.servicio')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='sac.usuario')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
    ]
